name: license
on:
  push:
    branches:
      - master
      - release-*
  workflow_dispatch: {}
  pull_request:
    branches:
      - master
      - release-*
      -
permissions:
  contents: read

jobs:
  license_check:
    runs-on: ubuntu-22.04
    name: Check for unapproved licenses
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install dependencies
        run: gem install license_finder
      - name: Run tests
        run: license_finder --decisions_file .license/dependency_decisions.yml